right_format = '$status'

[aws]
disabled = true
symbol = "  "

[conda]
symbol = " "

[character]
#success_symbol = "[❯](green)"
#error_symbol = "[❯](red)"

[dart]
symbol = " "

[directory]
read_only = " "
truncation_length = 0

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
style = "red"

[git_commit]
commit_hash_length = 8
only_detached = false
tag_disabled = false
tag_max_candidates = 10
tag_symbol = "  "

[git_status]
style = "bold yellow"
format = '([$all_status$ahead_behind]($style) )'
conflicted = ""
ahead = "⇡"
behind = "⇣"
diverged = "[](red)"
staged = "+"
untracked = "?"
modified = "*"

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[jobs]
disabled = true

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
disabled = true

[package]
symbol = " "

[perl]
symbol = " "

[php]
disabled = true
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[status]
disabled = false
format = '[$common_meaning $status]($style) '

[swift]
symbol = "ﯣ "

[time]
disabled = false
format = '[$time]($style) '

